Generating JWT, Sketch for database
arkes987/Offre pull request #7
Opened 2020-06-13 11:21 UTC by arkes987

Issues #2  and #4

- Added sketch for database with one User table.
- Added generating JWT token for user when exsist in database.

2020-06-13 12:05 UTC, wojciechowskiapp requested changes

2020-06-13 12:05 UTC, wojciechowskiapp commented on Offre.Controllers/Controllers/Authorize/Authorize.cs
>      [Route("[controller]")]
API should be constant. [controller] variable must be avoided if possible - it will prevent any inconsistencies late.

2020-06-13 12:05 UTC, wojciechowskiapp commented on Offre.Data/OffreContext.cs
> +            optionsBuilder.UseSqlServer(
connection string has to be placed inside a configuration file

2020-06-13 12:05 UTC, wojciechowskiapp commented on Offre.Logic/Authorize/AuthorizeLogic.cs
> +        private const string Secret = "L2zENCYuVozGOR9EQJN0";
SecretKey has to be 64bytes and placed inside a configuration file for the security reasons

2020-06-13 14:09 UTC, arkes987 commented on Offre.Controllers/Controllers/Authorize/Authorize.cs
>      [Route("[controller]")]
done

2020-06-13 14:09 UTC, arkes987 commented on Offre.Logic/Authorize/AuthorizeLogic.cs
> +        private const string Secret = "L2zENCYuVozGOR9EQJN0";
done

2020-06-13 14:09 UTC, arkes987 commented on Offre.Data/OffreContext.cs
> +            optionsBuilder.UseSqlServer(
done

2020-06-13 14:23 UTC, newbiedeveloper9 commented on Offre.Logic/Authorize/AuthorizeLogic.cs
> +        public string GenerateToken(long userId)
Most of the "Id" fields should be GUID type, not LONG.

2020-06-13 14:32 UTC, wojciechowskiapp approved these changes

2020-06-14 12:05 UTC, wojciechowskiapp approved these changes

2020-06-14 14:13 UTC, merged